### PR TITLE
Removes addResponsiveHandlers call in favor of store enhancer pattern

### PR DESCRIPTION
**Pull request by montemishkin**
See http://rackt.org/redux/docs/Glossary.html#store-enhancer for what a store enhancer is.

In summary, with this new api, a typical setup might look like:

```js
import {createStore, applyMiddleware, compose} from 'redux'
import {responsiveStoreEnhancer} from 'redux-responsive'
import thunk from 'redux-thunk'
import createLogger from 'redux-logger'
import reducer from './reducer'

const store = createStore(
    reducer,
    initialData,
    compose(
        responsiveStoreEnhancer,
        applyMiddleware(thunk, createLogger())
    )
)
```

### CODE REVIEW

**Comment by aaivazis** [comment]
fantastic! Thanks!

**Comment by aaivazis** [comment]
Since there's a breaking API change, i'm going to have to bump a major version number. Welcome to 1.0!

**Comment by aaivazis** [comment]
This looks good to me, merging and publish on npm. Thanks again

**Comment by montemishkin** [comment]
woohooo :fire:  1.0!

**Pull request merged**
